apiVersion: v1
kind: Service
metadata:
  name: {{ include "moses-chat-bot.fullname" . }}-frontend
  labels:
    {{- include "moses-chat-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moses-chat-bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moses-chat-bot.fullname" . }}-backend
  labels:
    {{- include "moses-chat-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moses-chat-bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
